### ISSUE TITLE
Is it correct to use MIT licence?

### ISSUE THREAD

**Issue by dannybouwers** [danmana/yed-azure-palettes#2]
Thank you for your work. I really appreciate it.

I noticed you've added MIT as a licence. I was wondering if this is correct since the script includes the SVG contents of Microsoft's icons in the *.grapml files.
As stated on Microsoft's download page, it isn't allowed to change the icon's in any way while this is allowed by the MIT licence.

I'm no licencing expert at all, so I don't know how this applies to generated files committed to the repository. Maybe it could simply be solved by publishing the *.graphml files as a release.

**Comment by danmana** [comment]
You are right, the icons themselves are probably not MIT.
I added the required information at the beginning of the README - https://github.com/danmana/yed-azure-palettes#icon-terms

I hope this covers it, I'm no licensing expert either.

**Comment by dannybouwers** [comment]
I hope so as well. Keep up the good work!
